# jgfs
# (c) 2013 Justin Gottula
# The source code of this project is distributed under the terms of the
# simplified BSD license. See the LICENSE file for details.

TIMESTAMP=$(shell date +'%Y%m%d-%H%M')

CC:=ccache gcc
AR:=ar

CFLAGS:=-std=gnu11 -O0 -ggdb -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -include stdbool.h -include stdint.h
LDFLAGS:=

DEFINES:=-D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26

FUSE_LIBS:=-lbsd -lfuse
MKFS_LIBS:=-lbsd
FSCK_LIBS:=-lbsd

JGFS_LIB:=bin/libjgfs.a
FUSE_BIN:=bin/jgfs
MKFS_BIN:=bin/mkjgfs
FSCK_BIN:=bin/jgfsck

LIB_OBJS=$(patsubst %.c,%.o,$(wildcard lib/*.c))
OBJS=$(patsubst %.c,%.o,$(wildcard src/*/*.c))


.PHONY: all clean backup lib fuse mkfs fsck

# default rule
all: lib fuse mkfs fsck

lib:  $(JGFS_LIB)
fuse: $(FUSE_BIN)
mkfs: $(MKFS_BIN)
fsck: $(FSCK_BIN)

clean:
	rm -rf $(wildcard bin/*) $(wildcard lib/*.o) $(wildcard lib/*.dep) $(wildcard src/*/*.o) $(wildcard src/*/*.dep)

backup:
	cd .. && tar -acvf backup/jgfs-$(TIMESTAMP).tar.xz jgfs/


$(JGFS_LIB): $(LIB_OBJS)
	rm -f $@
	$(AR) rcs $@ $^
$(FUSE_BIN): $(filter src/fuse/%.o,$(OBJS)) $(JGFS_LIB)
	$(CC) $(CFLAGS) $(FUSE_LIBS) -o $@ $^
$(MKFS_BIN): $(filter src/mkfs/%.o,$(OBJS)) $(JGFS_LIB)
	$(CC) $(CFLAGS) $(MKFS_LIBS) -o $@ $^
$(FSCK_BIN): $(filter src/fsck/%.o,$(OBJS)) $(JGFS_LIB)
	$(CC) $(CFLAGS) $(FSCK_LIBS) -o $@ $^


%.o: %.c Makefile
	$(CC) $(CFLAGS) $(DEFINES) -o $@ -Isrc -MP -MMD -MF $(<D)/$(patsubst %.c,%.dep,$(<F)) -c $<


# concatenate gcc's autogenerated dependencies
-include lib/*.dep
-include src/*/*.dep
