# jgfs
# (c) 2013 Justin Gottula
# The source code of this project is distributed under the terms of the
# simplified BSD license. See the LICENSE file for details.

CC:=gcc
CFLAGS:=-std=gnu11 -O2 -g -Wall -Wextra -flto
LDFLAGS:=
LIBS:=

# resolved when referenced
OBJS=$(patsubst %.c,%.o,$(wildcard src/*/*.c))


.PHONY: all clean mkfs

# default rule
all: mkfs

mkfs: bin/mkfs

clean:
	rm -rf $(wildcard bin/*) $(wildcard src/*/*.o) $(wildcard src/*/*.dep)


bin/mkfs: $(filter src/mkfs/%.o,$(OBJS))
	$(CC) $(CFLAGS) $(LIBS) -o $@ $^


%.o: %.c Makefile
	$(CC) $(CFLAGS) -o $@ -Isrc -c $<


# concatenate gcc's autogenerated dependencies
-include src/*/*.dep
